name: 'Hello World'

runs:
  using: "composite"
  steps:
      - name: fix connection delay
        continue-on-error: true
        if: ${{ fromJson(inputs.extras).delayFix == 'true' }}
        shell: bash
        run: |
          sed -i -e '/if !key.is_empty() && !token.is_empty() {/,/}/d' ./src/client.rs

      - name: add cycle monitors to toolbar
        continue-on-error: true
        if: fromJson(inputs.extras).cycleMonitor == 'true'
        run: |
          wget https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/cycle_monitor.diff
          git apply cycle_monitor.diff

      - name: use X for offline display instead of orange circle
        continue-on-error: true
        if: fromJson(inputs.extras).xOffline == 'true'
        run: |
          wget https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/xoffline.diff
          git apply xoffline.diff

      - name: hide-cm
        continue-on-error: true
        if: fromJson(inputs.extras).hidecm == 'true'
        run: |
          wget https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/hidecm.diff
          git apply hidecm.diff

      - name: statussort
        continue-on-error: true
        if: fromJson(inputs.extras).statussort == 'true'
        run: |
          wget https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/statussort.diff
          git apply statussort.diff

      - name: removeNewVersionNotif
        continue-on-error: true
        if: fromJson(inputs.extras).removeNewVersionNotif == 'true'
        run: |
          wget https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/removeNewVersionNotif.diff
          git apply removeNewVersionNotif.diff
